### PR TITLE
57 revisit example workflow

### PR DESCRIPTION
**Pull request by ahmedmohammed107**
Addressed all comments except for the second which I need to discuss further. We can make a new issue for it once we agree on what is to be done

### CODE REVIEW

**Comment by dlersch** [comment]
@ahmedmohammed107 , thank you for wrapping this up. I tested your code and it works fine. I only have a minor suggestion: The current code, if you just run it as is with `python example_workflow_v0.py` produces two files: `outputs` and `my_results`. The former is from hydra where all the logs are stored. The latter is where the images and such are stored. I would suggest to change the workflow such that it produces on output only. It is just confusing to the user why there are two files and what they actually mean.

**Comment by sgoldenCS** [comment]
@ahmedmohammed107, just to (hopefully) reduce any work you need to do, I believe you can set the default `logdir` to `${hydra:runtime.output_dir}/` if you want to store the results in the same "outputs" folder that Hydra uses.

**Comment by dlersch** [comment]
@sgoldenCS , @ahmedmohammed107 , yes. thank you Steven. I forgot to mention this. No need to write 100 more lines of codes, its just a change in settings for hydra.

**Comment by ahmedmohammed107** [comment]
@dlersch and @sgoldenCS, thank you. I now adjusted the workflow such that if no logdir is defined in the yaml file or if it is set as null, then it will be set as hydra's default output_dir

**Comment by dlersch** [comment]
tested the change, it works as it should. going to approve.

**Pull request merged**
